version: '3'
services:
  api:
    build: .
    ports:
       - 5000:5000
    command: python svc/app/api.py
    depends_on:
      - sqs
      - redis
  celery:
    build: .
    command: celery -A svc.tasks.tasks worker -Q default -l info
    depends_on:
      - sqs
      - redis
  redis:
    container_name: redis
    image: "redis:2.8"
    ports:
      - 6379:6379
  sqs:
    # for using forked version (alpine-sqs:dev), please clone https://github.com/galCohen88/alpine-sqs and run
    # $ docker-compose -f docker-compose.build up -d --build
    image: alpine-sqs:dev
    ports:
       - 9324:9324
       - 9325:9325
    container_name: alpine-sqs
